### ISSUE TITLE
local var type detection wrong after if statement

### ISSUE THREAD

**Issue by PabstMirror** [LordGolias/sqf#15]
```
private _condition = true;
if (isText (configFile >> "X")) then {
    _condition = getText (configFile >> "X");
    if (_condition == "") exitWith {_condition = true;};
    if (isNil _condition) then {};
};
```
```
[5,14]:error:Unary operator "isNil" only accepts argument of types [Code,String] (rhs is Boolean)
```
error goes away after removing `_condition = true;` from line 4

**Comment by PabstMirror** [comment]
Might be a better example, just using if-then-else
```
_litterCondition = "";
if (_litterCondition isEqualTo "") then {
    _litterCondition = {true};
} else {
    _litterCondition = compile _litterCondition; // [5,14]:error:Unary operator "isNil" only accepts argument of types [Code,String] (rhs is Boolean)
};
```

**Comment by LordGolias** [comment]
Thank you @PabstMirror for the report!

**Comment by PabstMirror** [comment]
1st example now passes, 2nd still has error.
It seems like it's related to being able to detect the type of `_a` initially as a string.
```
params ["_a"]; if (_a == "") then {_a = {true};} else {_a = compile _a;};
// error:Unary operator "compile" only accepts argument of types [String] (rhs is Code)

private _a = _this select 0; if (_a == "") then {_a = {true};} else {_a = compile _a;};
// error:Unary operator "compile" only accepts argument of types [String] (rhs is Code)

private _a = X; if (_a == "") then {_a = {true};} else {_a = compile _a;};
// error:Unary operator "compile" only accepts argument of types [String] (rhs is Code)

private _a = "false || true"; if (_a == "") then {_a = {true};} else {_a = compile _a;};
// Pass
```

**Comment by LordGolias** [comment]
I believe I nailed this one down. However, given a large number of branches in the solution, this may need to be re-opened.

Essentially, the current solution is:

Any initially undefined variable (globals or non-private locals) that is assigned a type in the script scope, becomes of that type. Any modification of its type on a higher scope (e.g. in `if`) makes it `undefined type`. (to be improved: if there is a new assignment in the script scope, make it defined again).

The same mechanism is used for private local variables, but instead of "script scope", use "current scope". 

In spirit, I think that this is the end goal; technically, I hope this is achieved and I made a set of tests to check it. 

@PabstMirror, could you try to find cases that break this?
