### ISSUE TITLE
Does not produce an error exit code if detected error

### ISSUE THREAD

**Issue by CreepPork** [LordGolias/sqf#26]
This can be a bit misleading when using Travis CI. When the SQF linter finds errors or warnings (can it be a configurable option, that when it detects a warning, it should exit with an error code of 1?), it still sends out an exit code of 0, meaning everything is OK, but it isn't.

**Comment by LordGolias** [comment]
First of all, I am very happy to know that this linter is being used in CI. That indicates a lot of trust on it from your side.

I agree with this. However, from the linter's perspective, exit code 0 means the linter was able to successfully parse the code.

In other words, the following things can happen:

1. linter fails to parse the code (an error in the linter itself)
2. linter parses the code and no errors are found
3. linter parses the code and errors are found

Three outcomes cannot be mapped to a exit with 0 exit with non-zero, and I do not think that different exit codes make a difference here.

A solution to this issue is to add a new parameter, `--exit` with the following possibilities:

1. `''`: always exit code 0 (default)
2. `'e'`: exit with code 1 when any error is found
3. `'w'`: exit with code 1 when any error or warning is found

The default is no error for backward compatibility. For example, [atom-linter](https://atom.io/packages/linter-sqf) assumes that exit code 0 means successful parsing (irrespectively of the sql errors found)

I pushed [a branch](https://github.com/LordGolias/sqf/tree/exit_code) with an implementation of this. Do you want to review it and see if it works for you?

**Comment by CreepPork** [comment]
I don't have the time to currently fully test in Travis but I played around with it seemed to be working fine.
