### ISSUE TITLE
Linter ignores different return types from ammoOnPylon

### ISSUE THREAD

**Issue by CreepPork** [LordGolias/sqf#31]
When using the 1.70 command [ammoOnPylon](https://community.bistudio.com/wiki/ammoOnPylon), it can return boolean or a number. The linter will display an error if the command is used in an if statement.

**Comment by SilentSpike** [comment]
🤔 A very interesting case, I'm half inclined to say it should error in this case because unless you're expecting the command to fail every time it shouldn't be used in an if statement (could just be replaced with `false` if you did expect it to fail every time).

**Comment by CreepPork** [comment]
@SilentSpike there is a type check before the if statement so it would always be correct.

**Comment by SilentSpike** [comment]
I believe this is because the command is considered to return type `Number` and not `Anything` as would be usual for a command with multiple return types (see only scalar is listed [here](https://github.com/intercept/intercept/blob/master/src/client/headers/client/sqf_pointers_declaration.hpp#L1251)).

Fix would be to add to the dict of [wrong return types](https://github.com/LordGolias/sqf/blob/master/build_database_with_returns.py#L55-L59) (I'm presuming the linter considers `Anything` a valid type to have in an if statement).

**Comment by LordGolias** [comment]
> I believe this is because the command is considered to return type Number and not Anything as would be usual for a command with multiple return types

This. We do not have a type representing multiple types (like Number or Boolean), so the simplest option would be to use Anything.
